# Spinor bases

In [1]:
# Force the local gqcpy to be imported
import sys
sys.path.insert(0, '../../build/gqcpy/')

import gqcpy
import numpy as np
np.set_printoptions(precision=3)

GQCP offers the capability to its users to work with different kinds of spinor bases. Let's explore the API of the spinor bases with a small example.

In [2]:
molecule = gqcpy.Molecule.ReadXYZ("../../gqcp/tests/data/h2_szabo.xyz" , 0)  # create a neutral molecule

## Restricted spinor bases

The one everyone is familiar with is a spinor basis whose alpha- and beta- expansion coefficients are equal. We call this spinor basis a restricted spinor basis `RSpinOrbitalBasis`.

In [3]:
r_spinor_basis = gqcpy.RSpinOrbitalBasis(molecule=molecule, basisset_name="STO-3G")

Constructing a spinor basis from a molecule and a basisset specification yields a non-orthogonal spinor basis, where the underlying scalar bases have been constructed by placing GTO shells on every atom of the molecule.

In [4]:
S_r = r_spinor_basis.quantizeOverlapOperator().parameters()
print(S_r)

[[1.    0.659]
 [0.659 1.   ]]


Since this initial basis is non-orthogonal, we should first try to orthonormalize it.

In [5]:
r_spinor_basis.lowdinOrthonormalize()

S_r = r_spinor_basis.quantizeOverlapOperator().parameters()
print(S_r)

[[1.00e+00 1.11e-16]
 [1.11e-16 1.00e+00]]


In [6]:
T = np.random.rand(2, 2)

In [7]:
g = r_spinor_basis.quantizeCoulombRepulsionOperator()
print(g.parameters())
g.transform(T)
print(g.parameters())

[[[[ 0.856 -0.006]
   [-0.006  0.494]]

  [[-0.006  0.011]
   [ 0.011 -0.006]]]


 [[[-0.006  0.011]
   [ 0.011 -0.006]]

  [[ 0.494 -0.006]
   [-0.006  0.856]]]]
[[[[0.003 0.008]
   [0.008 0.042]]

  [[0.008 0.028]
   [0.028 0.156]]]


 [[[0.008 0.028]
   [0.028 0.156]]

  [[0.042 0.156]
   [0.156 0.932]]]]


In [8]:
g_r = r_spinor_basis.quantizeCoulombRepulsionOperator().parameters()
print(g_r)

[[[[ 0.856 -0.006]
   [-0.006  0.494]]

  [[-0.006  0.011]
   [ 0.011 -0.006]]]


 [[[-0.006  0.011]
   [ 0.011 -0.006]]

  [[ 0.494 -0.006]
   [-0.006  0.856]]]]


## General spinor bases

General(ized) spinor bases have no restrictions on the expansion coefficients for the alpha- and beta spinors.

We can create them from a basisset specification in the same way as restricted spinor bases.

In [9]:
g_spinor_basis = gqcpy.GSpinorBasis(molecule, "STO-3G")

Similarly as in the restricted case, the spinor basis that is initialized here, is non-orthogonal.

In [10]:
S_g = g_spinor_basis.quantizeOverlapOperator().parameters()
print(S_g)

[[1.    0.659 0.    0.   ]
 [0.659 1.    0.    0.   ]
 [0.    0.    1.    0.659]
 [0.    0.    0.659 1.   ]]


We may, however, proceed by orthonormalizing it using a Löwdin orthonormalization step.

In [11]:
g_spinor_basis.lowdinOrthonormalize()

S_g = g_spinor_basis.quantizeOverlapOperator().parameters()
print(S_g)

[[1.000e+00 8.384e-17 0.000e+00 0.000e+00]
 [1.145e-16 1.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 1.000e+00 8.384e-17]
 [0.000e+00 0.000e+00 1.145e-16 1.000e+00]]


In [14]:
g_g = g_spinor_basis.quantizeCoulombRepulsionOperator().parameters()
print(g_g)

[[[[ 0.856 -0.006  0.     0.   ]
   [-0.006  0.494  0.     0.   ]
   [ 0.     0.     0.856 -0.006]
   [ 0.     0.    -0.006  0.494]]

  [[-0.006  0.011  0.     0.   ]
   [ 0.011 -0.006  0.     0.   ]
   [ 0.     0.    -0.006  0.011]
   [ 0.     0.     0.011 -0.006]]

  [[ 0.     0.     0.     0.   ]
   [ 0.     0.     0.     0.   ]
   [ 0.     0.     0.     0.   ]
   [ 0.     0.     0.     0.   ]]

  [[ 0.     0.     0.     0.   ]
   [ 0.     0.     0.     0.   ]
   [ 0.     0.     0.     0.   ]
   [ 0.     0.     0.     0.   ]]]


 [[[-0.006  0.011  0.     0.   ]
   [ 0.011 -0.006  0.     0.   ]
   [ 0.     0.    -0.006  0.011]
   [ 0.     0.     0.011 -0.006]]

  [[ 0.494 -0.006  0.     0.   ]
   [-0.006  0.856  0.     0.   ]
   [ 0.     0.     0.494 -0.006]
   [ 0.     0.    -0.006  0.856]]

  [[ 0.     0.     0.     0.   ]
   [ 0.     0.     0.     0.   ]
   [ 0.     0.     0.     0.   ]
   [ 0.     0.     0.     0.   ]]

  [[ 0.     0.     0.     0.   ]
   [ 0.     0.     0.     0